# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('head', models.CharField(max_length=150)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('birthday', models.DateField()),
                ('year', models.PositiveIntegerField()),
                ('wand', models.CharField(max_length=150)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='registry.House')),
            ],
        ),
    ]
